---
- name: Restart app
  command: sudo /bin/systemctl restart "{{ elixir_release_name }}"
  when: "ansible_service_mgr == 'systemd'"

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when: "ansible_service_mgr == 'systemd'"
  become: true
