- hosts: "*"
  environment:
    DATABASE_PASSWORD: "{{ database_password }}"
    SECRET_KEY_BASE: "{{ secret_key_base }}"
  tasks:
    - name: "Eval on shell"
      command: "/srv/phx-starter/current/bin/phx_starter eval {{ cmd }}"
